[package]
name = "reproto-repository"
version = "0.2.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/reproto/reproto"
homepage = "https://github.com/reproto/reproto"
documentation = "https://docs.rs/reproto-repository"
description = """
ReProto Repository
"""

[dependencies]
reproto-core = {path = "../core", version = "0.2"}

error-chain = "0.11"
toml = "0.4"
serde = {version = "1.0", features = ["rc"]}
serde_derive = "1.0"
serde_json = "1.0"
url = "1.5"
ring = "0.11"
log = "0.3"
hex = "0.2"
hyper = "0.11"
tokio-core = "0.1"
futures = "0.1"
