package service._1_0_0;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import common.Entry;
import io.grpc.BindableService;
import io.grpc.CallOptions;
import io.grpc.Channel;
import io.grpc.MethodDescriptor;
import io.grpc.MethodDescriptor.Marshaller;
import io.grpc.ServerServiceDefinition;
import io.grpc.stub.AbstractStub;
import io.grpc.stub.ClientCalls;
import io.grpc.stub.ServerCalls;
import io.grpc.stub.StreamObserver;
import io.reproto.MapperProvider;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.List;
import javax.annotation.Generated;

public interface MyService {
  public static final MethodDescriptor<Void, List<Entry>> METHOD_GET_POSTS = 
    MethodDescriptor.<Void, List<Entry>>newBuilder()
      .setType(MethodDescriptor.MethodType.UNKNOWN)
      .setFullMethodName(MethodDescriptor.generateFullMethodName("service._1_0_0.MyService", "get_posts"))
      .setRequestMarshaller(new VoidMarshaller())
      .setResponseMarshaller(new JsonMarshaller(new TypeReference<List<Entry>>(){}))
      .build();

  public static final MethodDescriptor<Entry, Void> METHOD_UPLOAD_POST = 
    MethodDescriptor.<Entry, Void>newBuilder()
      .setType(MethodDescriptor.MethodType.UNKNOWN)
      .setFullMethodName(MethodDescriptor.generateFullMethodName("service._1_0_0.MyService", "upload_post"))
      .setRequestMarshaller(new JsonMarshaller(new TypeReference<Entry>(){}))
      .setResponseMarshaller(new VoidMarshaller())
      .build();

  @Generated("Generated by ReProto")
  static class ClientStub extends AbstractStub<ClientStub> {
    public ClientStub(
      final Channel channel
    ) {
      super(channel);
    }

    public ClientStub(
      final Channel channel,
      final CallOptions callOptions
    ) {
      super(channel, callOptions);
    }

    @Override
    protected ClientStub build(final Channel channel, final CallOptions callOptions) {
      return new ClientStub(channel, callOptions);
    }

    /**
     * <pre>
     * Get all posts.
     * </pre>
     */
    StreamObserver<Void> getPosts(final StreamObserver<List<Entry>> observer) {
      return ClientCalls.asyncBidiStreamingCall(getChannel().newCall(METHOD_GET_POSTS, getCallOptions()), observer);
    }

    /**
     * <pre>
     * Upload the specified post.
     * </pre>
     */
    StreamObserver<Entry> uploadPost(final StreamObserver<Void> observer) {
      return ClientCalls.asyncBidiStreamingCall(getChannel().newCall(METHOD_UPLOAD_POST, getCallOptions()), observer);
    }
  }

  @Generated("Generated by ReProto")
  abstract static class ServerStub implements BindableService {
    /**
     * <pre>
     * Get all posts.
     * </pre>
     */
    public StreamObserver<Void> getPosts(final StreamObserver<List<Entry>> observer) {
      return ServerCalls.asyncUnimplementedStreamingCall(METHOD_GET_POSTS, observer);
    }

    /**
     * <pre>
     * Upload the specified post.
     * </pre>
     */
    public StreamObserver<Entry> uploadPost(final StreamObserver<Void> observer) {
      return ServerCalls.asyncUnimplementedStreamingCall(METHOD_UPLOAD_POST, observer);
    }

    @Override
    public ServerServiceDefinition bindService() {
      return ServerServiceDefinition
        .builder("service._1_0_0.MyService")
        .addMethod(METHOD_GET_POSTS, ServerCalls.asyncBidiStreamingCall(this::getPosts))
        .addMethod(METHOD_UPLOAD_POST, ServerCalls.asyncBidiStreamingCall(this::uploadPost))
        .build();
    }
  }

  public static class JsonMarshaller<T> implements MethodDescriptor.Marshaller<T> {
    private final ObjectMapper mapper;
    private final TypeReference<T> type;

    public JsonMarshaller(
      final TypeReference<T> type
    ) {
      this.mapper = MapperProvider.get();
      this.type = type;
    }

    @Override
    public T parse(final InputStream stream) {
      try {
        return this.mapper.readValue(stream, this.type);
      } catch (final Exception e) {
        throw new RuntimeException(e);
      }
    }

    @Override
    public InputStream stream(final T value) {
      final byte[] bytes;
      try {
        bytes = this.mapper.writeValueAsBytes(value);
      } catch (final Exception e) {
        throw new RuntimeException(e);
      }
      return new ByteArrayInputStream(bytes);
    }
  }

  public static class VoidMarshaller implements MethodDescriptor.Marshaller<Void> {
    @Override
    public Void parse(final InputStream stream) {
      return null;
    }

    @Override
    public InputStream stream(final Void value) {
      return new ByteArrayInputStream(new byte[0]);
    }
  }
}
