# default variable set for all themes
[default]
background_color = "#ffffff"
font_family = "Calibri, Candara, Segoe, Segoe UI, Optima, Arial, sans-serif"
font_size = "16px"
primitive_color = "#e6af69"
keyword_color = "#4b8c4b"
doc_h1_size = "120%"
doc_h2_size = "100%"
doc_h3_size = "100%"
doc_h4_size = "100%"
doc_h5_size = "100%"
doc_h6_size = "100%"
doc_header_color = "#4d76ae"
doc_border_color = "#dddddd"

name_part_color = "#9c9c9c"
name_package_color = "#4d76ae"
name_local_color = "#df3600"

[light]

[dark]
