# default variable set for all themes
# colors: http://paletton.com/#uid=34j0N0krYEdhdNimII0BNy6BLoK
[default]
margin="10px"
section_margin="40px"

heading_color="#C57100"
background_color="#FFFFFF"
link_color="#310B87"
title_color="#87BA00"

fonts="Verdana, Verdana, Geneva, sans-serif"
monospace_fonts="Lucida Console, Monaco5, monospace"

[light]

[dark]
